language: java
sudo: false

services:
  - redis-server
  
script:
  - mvn test -B -Dmaven.test.skip=false

matrix:
  include:
    - env: JDK='OpenJDK 8'
      jdk: openjdk8
    - env: JDK='OracleJDK 8'
      jdk: oraclejdk8
    - env: JDK='OpenJDK 9'
      install: . ./install-jdk.sh -F 9 -L GPL
    - env: JDK='OracleJDK 9'
      jdk: oraclejdk9
    - env: JDK='OpenJDK 10'
      install: . ./install-jdk.sh -F 10 -L GPL
    - env: JDK='OpenJDK 11'
      install: . ./install-jdk.sh -F 11 -L GPL
    - env: JDK='OpenJDK 12'
      install: . ./install-jdk.sh -F 12 -L GPL
    - env: JDK='OpenJDK 13'
      install: . ./install-jdk.sh -F 13 -L GPL
    - env: JDK='OpenJDK 14'
      install: . ./install-jdk.sh -F 14 -L GPL

before_install: wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh

after_success:
  - if [[ "${JDK}" == 'OpenJDK 8' && "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" == 'master' ]]; then
      mvn deploy --settings .travis-settings.xml -Dmaven.test.skip=true -B || travis_terminate 1;
    fi

cache:
  directories:
    - $HOME/.m2
